"""image migrations again

Revision ID: 141d806cc27e
Revises: 78a74c794348
Create Date: 2024-09-20 19:08:56.560463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141d806cc27e'
down_revision: Union[str, None] = '78a74c794348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booked_events', sa.Column('event_img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booked_events', 'event_img')
    # ### end Alembic commands ###
