"""database changes

Revision ID: 2a555f2588bb
Revises: 
Create Date: 2024-09-16 12:41:05.798975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a555f2588bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booked_events_email_fkey', 'booked_events', type_='foreignkey')
    op.create_foreign_key(None, 'booked_events', 'users', ['email'], ['email'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('events_event_creator_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'users', ['event_creator'], ['email'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_event_creator_fkey', 'events', 'users', ['event_creator'], ['email'], ondelete='CASCADE')
    op.drop_constraint(None, 'booked_events', type_='foreignkey')
    op.create_foreign_key('booked_events_email_fkey', 'booked_events', 'users', ['email'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###
