"""likes migration

Revision ID: 3bf99a852ebf
Revises: d7d6f13645ec
Create Date: 2024-09-17 15:31:01.100821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf99a852ebf'
down_revision: Union[str, None] = 'd7d6f13645ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'likes', ['liked_events'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='unique')
    # ### end Alembic commands ###
