"""likes migration

Revision ID: 8d637507c227
Revises: 2a555f2588bb
Create Date: 2024-09-17 12:15:02.612829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d637507c227'
down_revision: Union[str, None] = '2a555f2588bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('name', sa.String(), nullable=True))
    op.add_column('likes', sa.Column('email', sa.String(), nullable=True))
    op.add_column('likes', sa.Column('liked_events', sa.String(), nullable=True))
    op.create_foreign_key(None, 'likes', 'users', ['email'], ['email'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_column('likes', 'liked_events')
    op.drop_column('likes', 'email')
    op.drop_column('likes', 'name')
    # ### end Alembic commands ###
